### ISSUE TITLE
Feature request: Start on OS boot

### ISSUE THREAD

**Issue by SakuraIsayeki** [Processus-Thief/ETWMonitor#1]
With the utility of this (most excellent) software being monitoring activities, I'd love to see some form of automated start of ETWMonitor, straight after the OS boots up. This would limit the risk of the user forgetting to load ETWMonitor, potentially losing monitoring span for as long as it remains offline.

Perhaps consider evolving ETWMonitor into a Windows Service, which would also align itself nicely with some form of Monitoring Client & Collector Server architecture, all whilst allowing the OS itself to handle automatic service startup.

On another note, as a .NET dev myself, I'd be happy to provide assistance on developing this feature, if you'd like! And as always, thank you for bringing us this very nice piece of kit :)

**Comment by ProcessusT** [comment]
Hello,
yes it will be integrated in the client-server version because it is not possible to send toast notifications to the user's desktop from a service launched with system privileges.
The service must run with the user privileges and his password must be known to do that...

**Comment by SakuraIsayeki** [comment]
Thank you for the prompt reply. Inedeed, the debacle seems quite clear, with this permissions ordeal. 

As it could be a fair compromise, how about we setup ETWMonitor to launch on user login, for the standalone version? I see this as filling most usecases with a fair coverage, given most users login straight after OS boot. We could then setup a "launch silently in tray" behaviour, as you've already implemented a system tray feature :)

**Comment by ProcessusT** [comment]
Start on OS boot is now available in client-server version ! :)
Agent on client servers is started by a Windows service
